### ISSUE TITLE
Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'

### ISSUE THREAD

**Issue by Saurabh996** [evryfs/github-actions-runner-operator#440]
Hi team,

Getting 404 error for configuration step of runner: "./config.sh --url <repo> --token <token_value>".

Complete error details inserted below for reference:

![image](https://user-images.githubusercontent.com/28217592/172688105-9a288aff-fa10-4e28-bbbe-24d908ee5ca4.png)

Please help resolve the error/bug.

**Comment by Saurabh996** [comment]
Runner Image: Linux
Architecture: x64

Self-hosted on AWS EC2 instance.

@davidkarlsen Where should I check for logs from operator?

**Comment by davidkarlsen** [comment]
in the namespace where you deployed the operator, there will be a pod, see in that pod's logs

**Comment by Saurabh996** [comment]
Please find the logs below:

`
[2022-06-08 18:00:28Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/webFiles/bin'
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/webFiles'
[2022-06-08 18:00:28Z INFO HostContext] Well known config file 'Credentials': '/home/ubuntu/webFiles/.credentials'
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/webFiles/bin'
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/webFiles'
[2022-06-08 18:00:28Z INFO HostContext] Well known config file 'Runner': '/home/ubuntu/webFiles/.runner'
[2022-06-08 18:00:28Z INFO Listener] Runner is built for Linux (X64) - linux-x64.
[2022-06-08 18:00:28Z INFO Listener] RuntimeInformation: Linux 5.15.0-1008-aws #10-Ubuntu SMP Wed May 18 17:28:39 UTC 2022.
[2022-06-08 18:00:28Z INFO Listener] Version: 2.292.0
[2022-06-08 18:00:28Z INFO Listener] Commit: d4b794dd645e16990ae0530bf977e26ab24be9d9
[2022-06-08 18:00:28Z INFO Listener] Culture: 
[2022-06-08 18:00:28Z INFO Listener] UI Culture: 
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/webFiles/bin'
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/webFiles'
[2022-06-08 18:00:28Z INFO Listener] Validating directory permissions for: '/home/ubuntu/webFiles'
[2022-06-08 18:00:28Z INFO CommandLineParser] Parse
[2022-06-08 18:00:28Z INFO CommandLineParser] Parsing 5 args
[2022-06-08 18:00:28Z INFO CommandLineParser] parsing argument
[2022-06-08 18:00:28Z INFO CommandLineParser] HasArgs: False
[2022-06-08 18:00:28Z INFO CommandLineParser] Adding Command: configure
[2022-06-08 18:00:28Z INFO CommandLineParser] parsing argument
[2022-06-08 18:00:28Z INFO CommandLineParser] HasArgs: True
[2022-06-08 18:00:28Z INFO CommandLineParser] arg: url
[2022-06-08 18:00:28Z INFO CommandLineParser] parsing argument
[2022-06-08 18:00:28Z INFO CommandLineParser] HasArgs: True
[2022-06-08 18:00:28Z INFO CommandLineParser] Adding option 'url': 'https://github.com/Saurabh996/ec2Files_1p'
[2022-06-08 18:00:28Z INFO CommandLineParser] parsing argument
[2022-06-08 18:00:28Z INFO CommandLineParser] HasArgs: True
[2022-06-08 18:00:28Z INFO CommandLineParser] arg: token
[2022-06-08 18:00:28Z INFO CommandLineParser] parsing argument
[2022-06-08 18:00:28Z INFO CommandLineParser] HasArgs: True
[2022-06-08 18:00:28Z INFO CommandLineParser] Adding option 'token': '***'
[2022-06-08 18:00:28Z INFO Listener] Arguments parsed
[2022-06-08 18:00:28Z INFO Runner] ExecuteCommand
[2022-06-08 18:00:28Z INFO ConfigurationStore] currentAssemblyLocation: /home/ubuntu/webFiles/bin/Runner.Listener.dll
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/webFiles/bin'
[2022-06-08 18:00:28Z INFO ConfigurationStore] binPath: /home/ubuntu/webFiles/bin
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/webFiles/bin'
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/webFiles'
[2022-06-08 18:00:28Z INFO ConfigurationStore] RootFolder: /home/ubuntu/webFiles
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/webFiles/bin'
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/webFiles'
[2022-06-08 18:00:28Z INFO HostContext] Well known config file 'Runner': '/home/ubuntu/webFiles/.runner'
[2022-06-08 18:00:28Z INFO ConfigurationStore] ConfigFilePath: /home/ubuntu/webFiles/.runner
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/webFiles/bin'
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/webFiles'
[2022-06-08 18:00:28Z INFO HostContext] Well known config file 'Credentials': '/home/ubuntu/webFiles/.credentials'
[2022-06-08 18:00:28Z INFO ConfigurationStore] CredFilePath: /home/ubuntu/webFiles/.credentials
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/webFiles/bin'
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/webFiles'
[2022-06-08 18:00:28Z INFO HostContext] Well known config file 'MigratedCredentials': '/home/ubuntu/webFiles/.credentials_migrated'
[2022-06-08 18:00:28Z INFO ConfigurationStore] MigratedCredFilePath: /home/ubuntu/webFiles/.credentials_migrated
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/webFiles/bin'
[2022-06-08 18:00:28Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/webFiles'
[2022-06-08 18:00:28Z INFO HostContext] Well known config file 'Service': '/home/ubuntu/webFiles/.service'
[2022-06-08 18:00:28Z INFO ConfigurationStore] ServiceConfigFilePath: /home/ubuntu/webFiles/.service
[2022-06-08 18:00:28Z INFO CommandSettings] Flag 'help': 'False'
[2022-06-08 18:00:28Z INFO CommandSettings] Flag 'version': 'False'
[2022-06-08 18:00:28Z INFO CommandSettings] Flag 'commit': 'False'
[2022-06-08 18:00:28Z INFO CommandSettings] Flag 'check': 'False'
[2022-06-08 18:00:28Z INFO CommandSettings] Command 'configure': 'True'
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE: 
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE: |        ____ _ _   _   _       _          _        _   _                      |
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-06-08 18:00:28Z INFO Terminal] WRITE: |                       
[2022-06-08 18:00:28Z INFO Terminal] WRITE: Self-hosted runner registration
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE:                         |
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-06-08 18:00:28Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-06-08 18:00:28Z INFO ConfigurationManager] ConfigureAsync
[2022-06-08 18:00:28Z INFO ConfigurationStore] IsConfigured()
[2022-06-08 18:00:28Z INFO ConfigurationStore] IsConfigured: False
[2022-06-08 18:00:28Z INFO ConfigurationManager] Is configured: False
[2022-06-08 18:00:28Z INFO CommandSettings] Arg 'url': 'https://github.com/Saurabh996/ec2Files_1p'
[2022-06-08 18:00:28Z INFO CommandSettings] Remove url from Arg dictionary.
[2022-06-08 18:00:28Z INFO CommandSettings] Arg 'token': '***'
[2022-06-08 18:00:28Z INFO CommandSettings] Remove token from Arg dictionary.
[2022-06-08 18:00:29Z ERR  Terminal] WRITE ERROR: Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
[2022-06-08 18:00:29Z ERR  Terminal] WRITE ERROR: {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
[2022-06-08 18:00:29Z ERR  Runner] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.GetTenantCredential(String githubUrl, String githubToken, String runnerEvent)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[2022-06-08 18:00:29Z ERR  Terminal] WRITE ERROR: Response status code does not indicate success: 404 (Not Found).
[2022-06-08 18:00:29Z INFO Listener] Runner execution has finished with return code 1

`

**Comment by Saurabh996** [comment]
@davidkarlsen any update on this?

**Comment by davidkarlsen** [comment]
@Saurabh996 this is the log from the runner, and not the operator.
Do you see the registration token being updated as a secret in the target namespace, and have you mounted this?

**Comment by davidkarlsen** [comment]
no feedback, closing

**Comment by davidbirdog** [comment]
@Saurabh996  Do you fix the issue. I also encounter this issue.
